# Global variables

EXPLANATORY_VARIABLES = ['age',
                'blood_pressure_max',
                'blood_pressure_min',
                'pulse',
                'body_temperature',
                'spo2',
                'breathing',
                'jcs',
                'male',
                'arrhythmia',
                'dyspnea',
                'hand_sensation',
                'hand_moistening',
                'st_1',
                'st_2',
                'st_1_2',
                'roomair',
                'interview1',
                'interview2',
                'interview3',
                'interview4',
                'interview5',
                'interview6',
                'interview7',
                'interview8',
                'interview9',
                'interview10',
                'interview11',
                'interview12',
                'interview13',
                'interview14',
                'interview15',
                'interview16',
                'interview17',
                'interview18',
                'medical_history1',
                'medical_history2',
                'medical_history3',
                'medical_history4',
                'medical_history5',
                'medical_history6',
                'medical_history9',
                'medical_history10']


NUMERICAL_FEATURES =['age',
                'blood_pressure_max',
                'blood_pressure_min',
                'pulse',
                'body_temperature',
                'spo2',
                'breathing']


CATEGORICAL_FEATURES = ['jcs',
                'male',
                'arrhythmia',
                'dyspnea',
                'hand_sensation',
                'hand_moistening',
                'st_1',
                'st_2',
                'st_1_2',
                'roomair',
                'interview1',
                'interview2',
                'interview3',
                'interview4',
                'interview5',
                'interview6',
                'interview7',
                'interview8',
                'interview9',
                'interview10',
                'interview11',
                'interview12',
                'interview13',
                'interview14',
                'interview15',
                'interview16',
                'interview17',
                'interview18',
                'medical_history1',
                'medical_history2',
                'medical_history3',
                'medical_history4',
                'medical_history5',
                'medical_history6',
                'medical_history9',
                'medical_history10']


SELECTED_VARIABLES = ['age',
                    'blood_pressure_max',
                    'blood_pressure_min',
                    'pulse',
                    'body_temperature',
                    'spo2',
                    'breathing',
                    'male',
                    'dyspnea',
                    'st_2',
                    'st_1_2',
                    'interview7',
                    'interview8',
                    'interview9',
                    'interview10',
                    'interview15',
                    'interview18']


CORRESPONDENCE = {'heart rate': 'pulse',
         'room air': 'room air',
         'respiratory rate': 'breathing',
         'S1': 'hand_sensation',
         'S2': 'hand_moistening',
         'S3': 'dyspnea',
         'S4': 'interview1',
         'S5': 'interview2',
         'S6': 'interview3',
         'S7': 'interview4',
         'S8': 'interview5',
         'S9': 'interview6',
         'S10': 'interview7',
         'S11': 'interview8',
         'S12': 'interview9',
         'S13': 'interview10',
         'S14': 'interview11',
         'S15': 'interview12',
         'S16': 'interview13',
         'S17': 'interview14',
         'S18': 'interview15',
         'S19': 'interview16',
         'S20': 'interview17',
         'S21': 'interview18'}


DESCRIPTIONS = {'st_1_2': 'ST change',
                'st_2': 'ST elevation',
                'st_1': 'ST depression',
                'age': 'Age',
                'male': 'Male',
                'pulse': 'Heart rate',
                'body_temperature': 'Body Temperature',
                'spo2': 'Blood oxygen saturation',
                'dyspnea': 'Dyspnoea', #'Dyspnea', for American English
                'hand_sensation': 'Cold hands',
                'hand_moistening': 'Hand moistening',
                'interview1': 'Palpitations',
                'interview2': 'Throbbing pain',
                'interview3': 'Sharp/stabbing pain',
                'interview4': 'Positional chest pain',
                'interview5': 'Reproduction of chest pain by palpation',
                'interview6': 'Pain change by breathing or cough',
                'interview7': 'Pressing pain',
                'interview8': 'Nausea or vomiting',
                'interview9': 'Cold sweat',
                'interview10': 'Pain radiation to jaw or shoulder',
                'interview11': 'Similar to previous ischemic episode',
                'interview12': 'Chest pain aggravated by walk',
                'interview13': 'Worsening pain',
                'interview14': 'Pain at rest',
                'interview15': 'Persistent pain',
                'interview16': 'Recurrent pain with 24 hours',
                'interview17': 'Chronic pain',
                'interview18': 'Pain Severity (10-point scale)',
                'breathing': 'Respiratory rate',
                'blood_pressure_max': 'Systolic blood pressure',
                'blood_pressure_min': 'Diastolic blood pressure',
                'medical_history1': 'Diabetes mellitus',
                'medical_history2': 'Hypertension',
                'medical_history3': 'Dyslipidaemia',  #'Dyslipidemia' for American English
                'medical_history4': 'Stable angina',
                'medical_history5': 'Old myocardial infarction',
                'medical_history6': 'prior PCI',
                'medical_history9': 'Cerebral infarction',
                'medical_history10': 'Prior antiplatelet or anticoagulant therapy',
                'jcs': 'Japan Coma Scale',
                'roomair': 'Oxygen therapy',
                'arrhythmia': 'Arrhythmia'}
